"""empty message

Revision ID: a65df2191bdb
Revises: f70005b67962
Create Date: 2024-06-09 11:01:30.218594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a65df2191bdb'
down_revision = 'f70005b67962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('exp',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('exp',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
