"""empty message

Revision ID: a9c8a8116323
Revises: 
Create Date: 2024-06-09 10:30:36.276762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9c8a8116323'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatar',
    sa.Column('id_ava', sa.Integer(), nullable=False),
    sa.Column('gander', sa.String(length=10), nullable=False),
    sa.Column('vid', sa.String(length=30), nullable=False),
    sa.Column('path', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id_ava')
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('exp', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id_user')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_name'), ['name'], unique=True)

    op.create_table('chat',
    sa.Column('id_msg', sa.Integer(), nullable=False),
    sa.Column('msg', sa.String(length=4000), nullable=False),
    sa.Column('time_msg', sa.DateTime(), nullable=True),
    sa.Column('wrt_user', sa.Integer(), nullable=False),
    sa.Column('who', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['who'], ['user.id_user'], ),
    sa.ForeignKeyConstraint(['wrt_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_msg')
    )
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_who'), ['who'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_wrt_user'), ['wrt_user'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_wrt_user'))
        batch_op.drop_index(batch_op.f('ix_chat_who'))

    op.drop_table('chat')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_name'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('avatar')
    # ### end Alembic commands ###
