"""empty message

Revision ID: d299dc54f34c
Revises: a65df2191bdb
Create Date: 2024-06-09 11:02:44.553469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd299dc54f34c'
down_revision = 'a65df2191bdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('exp',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('exp',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
