"""empty message

Revision ID: f70005b67962
Revises: a9c8a8116323
Create Date: 2024-06-09 10:33:45.241135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f70005b67962'
down_revision = 'a9c8a8116323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventar',
    sa.Column('id_inv', sa.Integer(), nullable=False),
    sa.Column('name_object', sa.String(length=52), nullable=False),
    sa.PrimaryKeyConstraint('id_inv')
    )
    op.create_table('quest',
    sa.Column('id_quest', sa.Integer(), nullable=False),
    sa.Column('cont_quest', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_quest')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quest')
    op.drop_table('inventar')
    # ### end Alembic commands ###
